/*
 * generated by Xtext
 */
package istic.m2miage.idm;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class VideoGenRuntimeModule extends istic.m2miage.idm.AbstractVideoGenRuntimeModule {

}
