/*
 * generated by Xtext
 */
package istic.m2miage.idm.ui.contentassist

import istic.m2miage.idm.ui.contentassist.AbstractVideoGenProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class VideoGenProposalProvider extends AbstractVideoGenProposalProvider {
}
