/*
 * generated by Xtext
 */
package istic.m2miage.idm.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractVideoGenValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(istic.m2miage.idm.videoGen.VideoGenPackage.eINSTANCE);
		return result;
	}
}
