/*
 * generated by Xtext
 */
package istic.m2miage.idm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class VideoGenUiModule extends istic.m2miage.idm.ui.AbstractVideoGenUiModule {
	public VideoGenUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
