/*
 * generated by Xtext
 */
package istic.m2miage.idm.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import istic.m2miage.idm.ui.internal.VideoGenActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class VideoGenExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return VideoGenActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return VideoGenActivator.getInstance().getInjector(VideoGenActivator.ISTIC_M2MIAGE_IDM_VIDEOGEN);
	}
	
}
