/*
 * generated by Xtext
 */
package istic.m2miage.idm.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import istic.m2miage.idm.services.VideoGenGrammarAccess;

public class VideoGenParser extends AbstractContentAssistParser {
	
	@Inject
	private VideoGenGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected istic.m2miage.idm.ui.contentassist.antlr.internal.InternalVideoGenParser createParser() {
		istic.m2miage.idm.ui.contentassist.antlr.internal.InternalVideoGenParser result = new istic.m2miage.idm.ui.contentassist.antlr.internal.InternalVideoGenParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getVideoTypeAccess().getAlternatives(), "rule__VideoType__Alternatives");
					put(grammarAccess.getVideoGenAccess().getGroup(), "rule__VideoGen__Group__0");
					put(grammarAccess.getMandatoryAccess().getGroup(), "rule__Mandatory__Group__0");
					put(grammarAccess.getOptionalAccess().getGroup(), "rule__Optional__Group__0");
					put(grammarAccess.getAlternativesAccess().getGroup(), "rule__Alternatives__Group__0");
					put(grammarAccess.getVideoSeqAccess().getGroup(), "rule__VideoSeq__Group__0");
					put(grammarAccess.getVideoGenAccess().getVideotypesAssignment_2(), "rule__VideoGen__VideotypesAssignment_2");
					put(grammarAccess.getMandatoryAccess().getVideoAssignment_1(), "rule__Mandatory__VideoAssignment_1");
					put(grammarAccess.getOptionalAccess().getVideoAssignment_1(), "rule__Optional__VideoAssignment_1");
					put(grammarAccess.getAlternativesAccess().getNameAssignment_1(), "rule__Alternatives__NameAssignment_1");
					put(grammarAccess.getAlternativesAccess().getVideosAssignment_3(), "rule__Alternatives__VideosAssignment_3");
					put(grammarAccess.getVideoSeqAccess().getNameAssignment_1(), "rule__VideoSeq__NameAssignment_1");
					put(grammarAccess.getVideoSeqAccess().getPathAssignment_2(), "rule__VideoSeq__PathAssignment_2");
					put(grammarAccess.getVideoSeqAccess().getDureeAssignment_3(), "rule__VideoSeq__DureeAssignment_3");
					put(grammarAccess.getVideoSeqAccess().getDescriptionAssignment_4(), "rule__VideoSeq__DescriptionAssignment_4");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			istic.m2miage.idm.ui.contentassist.antlr.internal.InternalVideoGenParser typedParser = (istic.m2miage.idm.ui.contentassist.antlr.internal.InternalVideoGenParser) parser;
			typedParser.entryRuleVideoGen();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public VideoGenGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(VideoGenGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
