/**
 *
 * $Id$
 */
package playlist.validation;

import org.eclipse.emf.common.util.EList;

import playlist.Video;

/**
 * A sample validator interface for {@link playlist.Playlist}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PlaylistValidator {
	boolean validate();

	boolean validateVideo(EList<Video> value);
}
